site_name: Agent Evaluation
theme:
  name: material
  icon:
    annotation: material/plus-circle-outline 
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: white
    toggle:
      icon: material/weather-night
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: black
    toggle:
      icon: material/weather-sunny
      name: "Switch to light mode"
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.indexes
nav:
  - Home: index.md
  - User Guide: user_guide.md
  - Configuration: configuration.md
  - Evaluators:
    - evaluators/index.md
    - Amazon Bedrock:
      - evaluators/bedrock/claude.md
  - Targets:
    - targets/index.md
    - AWS:
      - targets/aws/bedrock_agents.md
      - targets/aws/q_business.md
      - targets/aws/sagemaker_endpoints.md
  - Reference:
    - cli: reference/cli.md
    - conversation_handler: reference/conversation_handler.md
    - evaluator: reference/evaluator.md
    - hook: reference/hook.md
    - target: reference/target.md
    - test: reference/test.md
    - test_result: reference/test_result.md
    - trace_handler: reference/trace_handler.md

repo_url: https://github.com/awslabs/agent-evaluation
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - mkdocs-click
extra_css:
  - stylesheets/extra.css
plugins:
- search
- mkdocstrings
